id: ABA5A3432
title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice of
  the Great Compassionate One, Natural Liberation of Suffering from The Heart-Essence
  of the Vast Expanse'
type: translation
pechas:
- ID5FBC94B
- I5EB0C411
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:34.438425
  last_modified_at: 2023-01-04 11:44:34.438436
  collections:
  - Dodrupchen Jigme Trinle Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  ID5FBC94B/77E9: 13B1
  I5EB0C411/1935: 13B1
